services:
  api1: &api
    image: ghcr.io/gabrielrauch/rinha-2026:f6b661ace4c5f5baf6bbb0d13479f4e60cab492d
    environment:
      - RINHA_FD_SOCK=/run/sock/api1.sock
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api2:
    <<: *api
    environment:
      - RINHA_FD_SOCK=/run/sock/api2.sock

  lb:
    image: ghcr.io/gabrielrauch/rinha-2026-lb:f6b661ace4c5f5baf6bbb0d13479f4e60cab492d
    restart: always
    depends_on:
      - api1
      - api2
    environment:
      - PORT=9999
      - FD_UPSTREAMS=/run/sock/api1.sock,/run/sock/api2.sock
      - WORKERS=2
    ports:
      - "9999:9999"
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
volumes:
  sock:
