services:
  api1: &api
    image: ghcr.io/gabrielrauch/rinha-2026:9cbd82ea0fd1783365dca3593291866a3bac88aa
    environment:
      - RINHA_SOCK=/run/sock/api1.sock
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "160M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    security_opt:
      - seccomp:unconfined

  api2:
    <<: *api
    environment:
      - RINHA_SOCK=/run/sock/api2.sock

  lb:
    image: ghcr.io/gabrielrauch/rinha-2026-lb:9cbd82ea0fd1783365dca3593291866a3bac88aa
    restart: always
    depends_on:
      - api1
      - api2
    environment:
      - PORT=9999
      - UPSTREAMS=/run/sock/api1.sock,/run/sock/api2.sock
    ports:
      - "9999:9999"
    volumes:
      - sock:/run/sock
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    security_opt:
      - seccomp:unconfined
volumes:
  sock:
